# Module Configuration File
#
# This file configures Hugo module settings, particularly module mounts which
# define how content is organized within the project.
#
# Mounts specify file paths in your project that Hugo should use when building
# the site. They allow for custom directory structures and integrating content
# from different locations.

mounts:
  # content
  - source: content/fr
    target: content
    lang: fr

  - source: content/en
    target: content
    lang: en

  # data
  - source: node_modules/@thulite/doks-core/data
    target: data

  - source: data
    target: data

  # layouts
  - source: layouts
    target: layouts

  - source: node_modules/@thulite/doks-core/layouts
    target: layouts

  - source: node_modules/@thulite/core/layouts
    target: layouts

  - source: node_modules/@thulite/seo/layouts
    target: layouts

  - source: node_modules/@thulite/images/layouts
    target: layouts

  - source: node_modules/@thulite/inline-svg/layouts
    target: layouts

  # i18n
  - source: node_modules/@thulite/doks-core/i18n
    target: i18n

  - source: i18n
    target: i18n

  # archetypes
  - source: node_modules/@thulite/doks-core/archetypes
    target: archetypes

  - source: archetypes
    target: archetypes

  # assets
  - source: node_modules/@thulite/core/assets
    target: assets

  - source: node_modules/@thulite/doks-core/assets
    target: assets

  - source: node_modules/@thulite/images/assets
    target: assets

  - source: node_modules/@tabler/icons/icons
    target: assets/svgs/all-svg-icons/tabler-icons

  - source: assets
    target: assets

  # static
  - source: node_modules/@thulite/doks-core/static
    target: static

  - source: static
    target: static
